before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y hunspell hunspell-ru hunspell-en-us

script:
  - git diff HEAD^ | hunspell -d ru_RU,en_US | grep "^&"

notifications:
  email: false
