language: go
sudo: required

dist: trusty

git:
  depth: 3
  submodules: false

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - sudo env PATH=$PATH GOPATH=$GOPATH bash files/check-install.sh

script:
  - bash files/check.sh

notifications:
  email: false
