language: go
  go:
    - 1.9

#sudo: required
before_install:
#  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
#  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - sh files/check-install.sh

script:
  - sh files/check.sh

notifications:
  email: false
