version: "3.2"

services:
  ru_de_checker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ru_de_checker
    user: travis
    command: bash -c "env && cd /home/travis/ru-de-faq && sh files/check.sh"
    volumes:
      - ../.:/home/travis/ru-de-faq
