name: Continious integration

on:
  pull_request:

jobs:
  spell_and_dead_links_checks:
    if: github.repository == 'ru-de/faq'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.14.1'
      - name: setup env
        run: |
          echo "::set-env name=GOPATH::$(dirname $GITHUB_WORKSPACE)"
          echo "::add-path::$(dirname $GITHUB_WORKSPACE)/bin"
        shell: bash
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: src/github.com/${{ github.repository }}
      - name: Install utils
        run: |
          sudo bash files/check-install.sh
      - name: Check spell and dead links
        run: |
           true
