name: Sort dictionary

on:
  push:
    branches:
      - master
      - gh-actions

jobs:
  sort_dictionary:
    if: github.repository == 'ru-de/faq'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: sort
        run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "Github Actions"
            LC_ALL=ru_RU.UTF8 sort files/dictionary.dic -o files/dictionary.dic -f
            ! git diff --quiet && git commit -q -am "dictionary rearrangement" && git push
