name: Update github pages

on:
  push:
    branches:
      - master
      - gh-actions

jobs:
  update:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.14.1'

      - name: update
        run: |
          go version
          git branch ci_pull_request
          git status
          git branch